version: 2
jobs:
  macOS_swift_4.1:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test
      - run: make build
  macOS_swift_4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test
      - run: make build
workflows:
  version: 2
  workflow:
    jobs:
      - macOS_swift_4.1
      - macOS_swift_4.2
